version: '3'
services:
  app:
    build: .
    ports:
     - "5000:5000"
    environment:
     - DISPLAY=${HOSTNAME}:0
    volumes:
     - "./src:/opt/catkin_ws/src"
     - "./test_data:/opt/catkin_ws/test_data"
     - "./.catkin_workspace:/opt/catkin_ws/.catkin_workspace"
     - "/tmp/.X11-unix:/tmp/.X11-unix"
